name: 'Github action to deploy Django app'
description: ''
inputs:
  name:
    description: 'Enter your name'
    required: true
    default: "1"
outputs:
  text:
    value: ${{ steps.get-text.outputs.num_squared }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Pass Inputs to Shell
      run: |
        echo "INPUT_NAME=${{ inputs.name }}" >> $GITHUB_ENV
      shell: bash
    - name: Get hello world text
      id: get-text
      run: python src/main.py
      shell: bash